-- MySQL Script generated by MySQL Workbench
-- Sat Feb 26 21:56:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbcolegio_preg3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcolegio_preg3_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcolegio_preg3_1` DEFAULT CHARACTER SET utf8 ;
USE `dbcolegio_preg3_1` ;

-- -----------------------------------------------------
-- Table `dbcolegio_preg3`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcolegio_preg3_1`.`Curso` (
  `idCurso` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(256) NULL,
  `Precio` DECIMAL(11,2) NOT NULL,
  `Horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcolegio_preg3`.`Pofesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcolegio_preg3_1`.`Pofesor` (
  `idPofesor` INT NOT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  `Foto` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(256) NULL,
  PRIMARY KEY (`idPofesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcolegio_preg3`.`Nosotros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcolegio_preg3_1`.`Nosotros` (
  `idNosotros` INT NOT NULL,
  `Profesor` INT NOT NULL,
  PRIMARY KEY (`idNosotros`, `Profesor`),
  INDEX `fk_nosotros_profesor_idx` (`Profesor` ASC) VISIBLE,
  CONSTRAINT `fk_nosotros_profesor`
    FOREIGN KEY (`Profesor`)
    REFERENCES `dbcolegio_preg3_1`.`Pofesor` (`idPofesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcolegio_preg3`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcolegio_preg3_1`.`Alumno` (
  `DNI` CHAR(8) NOT NULL,
  `Nombre` VARCHAR(200) NOT NULL,
  `Celular` VARCHAR(9) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`DNI`),
  UNIQUE INDEX `Celular_UNIQUE` (`Celular` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcolegio_preg3`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcolegio_preg3_1`.`Matricula` (
  `idMatricula` INT NOT NULL,
  `IdAlumno` CHAR(8) NOT NULL,
  `Fecha_Matricula` DATE NOT NULL,
  `Total` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idMatricula`, `IdAlumno`),
  UNIQUE INDEX `IdAlumno_UNIQUE` (`IdAlumno` ASC) VISIBLE,
  UNIQUE INDEX `idMatriculas_UNIQUE` (`idMatricula` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_alumno`
    FOREIGN KEY (`IdAlumno`)
    REFERENCES `dbcolegio_preg3_1`.`Alumno` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcolegio_preg3`.`DetalleMatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcolegio_preg3_1`.`DetalleMatricula` (
  `idDetalleMatricula` INT NOT NULL,
  `IdMatricula` INT NOT NULL,
  `IdCurso` INT NOT NULL,
  `Horario` VARCHAR(45) NOT NULL,
  `Subtotal` DECIMAL(11,2) NOT NULL,
  `Fecha_Inicio` DATE NOT NULL,
  `Fecha_Fin` DATE NOT NULL,
  PRIMARY KEY (`idDetalleMatricula`, `IdMatricula`, `IdCurso`),
  UNIQUE INDEX `idDetalleMatricula_UNIQUE` (`idDetalleMatricula` ASC) VISIBLE,
  INDEX `fk_detalle_matricula_idx` (`IdMatricula` ASC) VISIBLE,
  INDEX `fk_detalle_curso_idx` (`IdCurso` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_matricula`
    FOREIGN KEY (`IdMatricula`)
    REFERENCES `dbcolegio_preg3_1`.`Matricula` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_curso`
    FOREIGN KEY (`IdCurso`)
    REFERENCES `dbcolegio_preg3_1`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcolegio_preg3`.`alumno_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcolegio_preg3_1`.`alumno_curso` (
  `idAlumno` CHAR(8) NOT NULL,
  `idCurso` INT NOT NULL,
  INDEX `fk_alumnocurso_alumno_idx` (`idAlumno` ASC) VISIBLE,
  INDEX `fk_alumnocurso_curso_idx` (`idCurso` ASC) VISIBLE,
  PRIMARY KEY (`idCurso`, `idAlumno`),
  CONSTRAINT `fk_alumnocurso_alumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `dbcolegio_preg3_1`.`Alumno` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnocurso_curso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `dbcolegio_preg3_1`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcolegio_preg3`.`Curso_has_Pofesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcolegio_preg3_1`.`Curso_has_Pofesor` (
  `Curso_idCurso` INT NOT NULL,
  `Pofesor_idPofesor` INT NOT NULL,
  PRIMARY KEY (`Curso_idCurso`, `Pofesor_idPofesor`),
  INDEX `fk_Curso_has_Pofesor_Pofesor1_idx` (`Pofesor_idPofesor` ASC) VISIBLE,
  INDEX `fk_Curso_has_Pofesor_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_has_Pofesor_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `dbcolegio_preg3_1`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Pofesor_Pofesor1`
    FOREIGN KEY (`Pofesor_idPofesor`)
    REFERENCES `dbcolegio_preg3_1`.`Pofesor` (`idPofesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
